name: pixanalyzer
channels:
  - defaults
dependencies:
  - pip=23.2.1
  - python=3.12.0

  - pip:
    - contourpy==1.1.1
    - cycler==0.12.0
    - fonttools==4.43.0
    - kiwisolver==1.4.5
    - matplotlib==3.8.0
    - numpy==1.26.0
    - opencv-python==4.8.1.78
    - packaging==23.2
    - pandas==2.1.1
    - pillow==10.0.1
    - pyparsing==3.1.1
    - pysimplegui==4.60.5
    - python-dateutil==2.8.2
    - pytz==2023.3.post1
    - seaborn==0.13.0
    - six==1.16.0
    - tqdm==4.66.1
    - tzdata==2023.3
